steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build","-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/containers/${_SERVICE}:${SHORT_SHA}","apps/workers/${_SERVICE}"]
  - name: gcr.io/cloud-builders/docker
    args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/containers/${_SERVICE}:${SHORT_SHA}"]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/containers/${_SERVICE}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --min-instances=0
      - --max-instances=10
      - --no-allow-unauthenticated
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/containers/${_SERVICE}:${SHORT_SHA}
substitutions:
  _REGION: us-central1
  _SERVICE: parser-worker
options:
  logging: CLOUD_LOGGING_ONLY
