[project]
name = "bv-api"
version = "0.1.0"
dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]",
  "pydantic>=2.5",
  "sqlalchemy[asyncio]>=2.0",
  "asyncpg",
  "google-cloud-storage",
  "google-cloud-pubsub",
]
